# Generated by Django 5.2 on 2026-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KoreanRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('cosplay_friendly', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAndCosplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('COSPLAY', '韓國 CosPlay 地點分享'), ('PLAN', '韓國特色夢幻旅遊計劃'), ('NOTICE', '韓國旅遊注意事項出遊分享')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('photo', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
